### ISSUE TITLE
Mentor status breaks everything but name

### ISSUE THREAD

**Issue by ipsumata** [Poliwrath/ffxiv-discord-rpc#2]
When online status is set to any type of Mentor (see one example below) all of the rich presence (but the name) doesn't work.

![ffxiv_dx11_2018-01-19_12-06-09](https://user-images.githubusercontent.com/8314858/35150182-3e7e740e-fd11-11e7-9c9a-91c9577265f5.png)

![discordcanary_2018-01-19_12-05-56](https://user-images.githubusercontent.com/8314858/35150174-37fe41c2-fd11-11e7-8d57-e962c20f1455.png)

**Comment by ipsumata** [comment]
I have also found the same issue with the 'Looking to Meld Materia' status

**Comment by ipsumata** [comment]
I've forked this with some better/more icons, tried to rebuild it myself with the filename as 'Mentor2' as that is the term used by sharlayan but it still doesn't work. Not quite sure how to fix it

**Comment by Poliwrath** [comment]
Hi! I fixed it. 

(for anyone wondering how/what/why):

The icons are stored on the discord app registered to my account. Editing the contents of the icons does nothing, they're only there in case you want to upload them all to your own app or make a PR with new ones. 

And, the icon was just named Mentor when the actual status is Mentor2, so I just had to reupload the icon with the fixed name.
